### ISSUE TITLE
Cannot deploy the appyter-catalog

### ISSUE THREAD

**Issue by hengkp** [MaayanLab/appyter-catalog#867]
Hi,

I tried to run appyter-catalog on my Linux machine, and it threw an error below. Do you have any suggestions to solve this issue?

I appreciate any help you can provide.
Heng

```
(base) nodeadmin@node1:/galaxy-app$ git clone https://github.com/MaayanLab/appyter-catalog.git
Cloning into 'appyter-catalog'...
remote: Enumerating objects: 17894, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 17894 (delta 31), reused 32 (delta 16), pack-reused 17839
Receiving objects: 100% (17894/17894), 187.81 MiB | 16.80 MiB/s, done.
Resolving deltas: 100% (12025/12025), done.
Updating files: 100% (1671/1671), done.
```
```
(base) nodeadmin@node1:/galaxy-app$ cd appyter-catalog/
```
```
(base) nodeadmin@node1:/galaxy-app/appyter-catalog$ make deploy
cd app && npm i && npm run build && cd .. && docker-compose build appyters-catalog && touch app/.build

added 372 packages, and audited 373 packages in 14s

52 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> appyter-catalog@1.1.1 build
> webpack -c webpack.config.js --mode production

[webpack-cli] Failed to load '/galaxy-app/appyter-catalog/app/webpack.config.js' config
[webpack-cli] Error: ENOENT: no such file or directory, open 'public/appyters.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at file:///galaxy-app/appyter-catalog/app/src/index.html.js:3:35
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async WebpackCLI.tryRequireThenImport (/galaxy-app/appyter-catalog/app/node_modules/webpack-cli/lib/webpack-cli.js:213:26)
    at async loadConfigByPath (/galaxy-app/appyter-catalog/app/node_modules/webpack-cli/lib/webpack-cli.js:1404:27)
    at async Promise.all (index 0) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'public/appyters.json'
}
make: *** [Makefile:42: app/.build] Error 2
```

**Comment by hengkp** [comment]
Thank you for your information. I will follow your instruction to run locally.
